In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\envs\pythondatascienceproject\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\envs\pythondatascienceproject\lib\site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\envs\pythondatascienceproject\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\envs\pythondatascienceproject\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\envs\pythondatascienceproject\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\envs\pythondatascienceproject\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r'C:\Users\user\OneDrive\Desktop\Student Mental health.csv')

In [5]:
print(df)

            Timestamp Choose your gender   Age What is your course?  \
0    08-07-2020 12:02             Female  18.0          Engineering
1    08-07-2020 12:04               Male  21.0    Islamic education
2    08-07-2020 12:05               Male  19.0                  BIT
3    08-07-2020 12:06             Female  22.0                 Laws
4    08-07-2020 12:13               Male  23.0         Mathemathics
..                ...                ...   ...                  ...
96   13-07-2020 19:56             Female  21.0                  BCS
97   13-07-2020 21:21               Male  18.0          Engineering
98   13-07-2020 21:22             Female  19.0             Nursing
99   13-07-2020 21:23             Female  23.0     Pendidikan Islam
100  18-07-2020 20:16               Male  20.0   Biomedical science

    Your current year of Study What is your CGPA? Marital status  \
0                       year 1        3.00 - 3.49             No
1                       year 2        3.00 - 3.49             No
2                       Year 1        3.00 - 3.49             No
3                       year 3        3.00 - 3.49            Yes
4                       year 4        3.00 - 3.49             No
..                         ...                ...            ...
96                      year 1        3.50 - 4.00             No
97                      Year 2        3.00 - 3.49             No
98                      Year 3        3.50 - 4.00            Yes
99                      year 4        3.50 - 4.00             No
100                     Year 2        3.00 - 3.49             No

    Do you have Depression? Do you have Anxiety? Do you have Panic attack?  \
0                       Yes                   No                       Yes
1                        No                  Yes                        No
2                       Yes                  Yes                       Yes
3                       Yes                   No                        No
4                        No                   No                        No
..                      ...                  ...                       ...
96                       No                  Yes                        No
97                      Yes                  Yes                        No
98                      Yes                   No                       Yes
99                       No                   No                        No
100                      No                   No                        No

    Did you seek any specialist for a treatment?
0                                             No
1                                             No
2                                             No
3                                             No
4                                             No
..                                           ...
96                                            No
97                                            No
98                                            No
99                                            No
100                                           No

[101 rows x 11 columns]

In [6]:
df.head()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,08-07-2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,08-07-2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,08-07-2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,08-07-2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,08-07-2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [7]:
df.tail()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
96,13-07-2020 19:56,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,13-07-2020 21:21,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,13-07-2020 21:22,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
99,13-07-2020 21:23,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No
100,18-07-2020 20:16,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    object
 1   Choose your gender                            101 non-null    object
 2   Age                                           100 non-null    float64
 3   What is your course?                          101 non-null    object
 4   Your current year of Study                    101 non-null    object
 5   What is your CGPA?                            101 non-null    object
 6   Marital status                                101 non-null    object
 7   Do you have Depression?                       101 non-null    object
 8   Do you have Anxiety?                          101 non-null    object
 9   Do you have Panic attack?                     101 non-null    object
 10  Did you seek any specialist for a treatment?  101 non-null    object
dtypes: float64(1), object(10)
memory usage: 8.8+ KB

In [9]:
df.isnull().sum()

Timestamp                                       0
Choose your gender                              0
Age                                             1
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              0
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
dtype: int64