In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
df = pd.read_csv(r'C:\Users\user\OneDrive\Desktop\Student Mental health.csv')

In [39]:
print(df)

            Timestamp Choose your gender   Age What is your course?  \
0    08-07-2020 12:02             Female  18.0          Engineering
1    08-07-2020 12:04               Male  21.0    Islamic education
2    08-07-2020 12:05               Male  19.0                  BIT
3    08-07-2020 12:06             Female  22.0                 Laws
4    08-07-2020 12:13               Male  23.0         Mathemathics
..                ...                ...   ...                  ...
96   13-07-2020 19:56             Female  21.0                  BCS
97   13-07-2020 21:21               Male  18.0          Engineering
98   13-07-2020 21:22             Female  19.0             Nursing
99   13-07-2020 21:23             Female  23.0     Pendidikan Islam
100  18-07-2020 20:16               Male  20.0   Biomedical science

    Your current year of Study What is your CGPA? Marital status  \
0                       year 1        3.00 - 3.49             No
1                       year 2        3.00 - 3.49             No
2                       Year 1        3.00 - 3.49             No
3                       year 3        3.00 - 3.49            Yes
4                       year 4        3.00 - 3.49             No
..                         ...                ...            ...
96                      year 1        3.50 - 4.00             No
97                      Year 2        3.00 - 3.49             No
98                      Year 3        3.50 - 4.00            Yes
99                      year 4        3.50 - 4.00             No
100                     Year 2        3.00 - 3.49             No

    Do you have Depression? Do you have Anxiety? Do you have Panic attack?  \
0                       Yes                   No                       Yes
1                        No                  Yes                        No
2                       Yes                  Yes                       Yes
3                       Yes                   No                        No
4                        No                   No                        No
..                      ...                  ...                       ...
96                       No                  Yes                        No
97                      Yes                  Yes                        No
98                      Yes                   No                       Yes
99                       No                   No                        No
100                      No                   No                        No

    Did you seek any specialist for a treatment?
0                                             No
1                                             No
2                                             No
3                                             No
4                                             No
..                                           ...
96                                            No
97                                            No
98                                            No
99                                            No
100                                           No

[101 rows x 11 columns]

In [40]:
df.head()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,08-07-2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,08-07-2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,08-07-2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,08-07-2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,08-07-2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [41]:
df.tail()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
96,13-07-2020 19:56,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,13-07-2020 21:21,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,13-07-2020 21:22,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
99,13-07-2020 21:23,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No
100,18-07-2020 20:16,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    object
 1   Choose your gender                            101 non-null    object
 2   Age                                           100 non-null    float64
 3   What is your course?                          101 non-null    object
 4   Your current year of Study                    101 non-null    object
 5   What is your CGPA?                            101 non-null    object
 6   Marital status                                101 non-null    object
 7   Do you have Depression?                       101 non-null    object
 8   Do you have Anxiety?                          101 non-null    object
 9   Do you have Panic attack?                     101 non-null    object
 10  Did you seek any specialist for a treatment?  101 non-null    object
dtypes: float64(1), object(10)
memory usage: 8.8+ KB

In [43]:
df.isnull().sum()

Timestamp                                       0
Choose your gender                              0
Age                                             1
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              0
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
dtype: int64

In [44]:
df.loc[df["Do you have Depression?"] == "Yes", "Do you have Depression?"] = 1
df.loc[df["Do you have Depression?"] == "No", "Do you have Depression?"] = 0
df.sample(10)

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
13,08-07-2020 12:41,Male,19.0,Engineering,year 1,3.00 - 3.49,No,0,No,No,No
82,13-07-2020 10:12,Female,19.0,Engineering,year 1,3.00 - 3.49,No,1,Yes,No,No
23,08-07-2020 13:15,Female,24.0,Engineering,year 1,3.00 - 3.49,No,0,No,No,No
57,08-07-2020 16:21,Female,20.0,BENL,Year 3,3.00 - 3.49,No,1,Yes,No,No
61,08-07-2020 16:53,Female,19.0,BCS,year 1,3.50 - 4.00,No,0,No,No,No
14,08-07-2020 12:43,Female,18.0,KENMS,Year 2,3.50 - 4.00,No,0,Yes,No,No
12,08-07-2020 12:40,Female,18.0,BCS,year 1,3.00 - 3.49,No,1,No,No,No
95,13-07-2020 19:08,Female,18.0,Islamic Education,year 1,3.50 - 4.00,No,0,No,No,No
21,08-07-2020 13:13,Female,18.0,KOE,Year 2,3.00 - 3.49,No,0,No,No,No
56,08-07-2020 16:08,Male,23.0,Kirkhs,Year 3,3.50 - 4.00,No,0,No,No,No

In [45]:
df.loc[df["Do you have Anxiety?"] == "Yes", "Do you have Anxiety?"] = 1
df.loc[df["Do you have Anxiety?"] == "No", "Do you have Anxiety?"] = 0
df.sample(10)

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
7,08-07-2020 12:33,Female,18.0,BCS,year 1,3.50 - 4.00,No,0,1,No,No
70,08-07-2020 20:36,Female,24.0,Biomedical science,year 1,3.00 - 3.49,No,0,0,No,No
83,13-07-2020 10:12,Female,19.0,Pendidikan Islam,Year 2,3.00 - 3.49,No,0,0,No,No
47,08-07-2020 15:14,Female,18.0,Engine,year 4,3.50 - 4.00,No,0,0,No,No
33,08-07-2020 14:31,Male,18.0,BCS,Year 2,3.50 - 4.00,Yes,1,1,No,Yes
67,08-07-2020 18:11,Male,19.0,MHSC,Year 3,3.00 - 3.49,Yes,1,0,Yes,No
56,08-07-2020 16:08,Male,23.0,Kirkhs,Year 3,3.50 - 4.00,No,0,0,No,No
29,08-07-2020 14:05,Female,24.0,BCS,year 4,3.50 - 4.00,No,0,0,No,No
21,08-07-2020 13:13,Female,18.0,KOE,Year 2,3.00 - 3.49,No,0,0,No,No
3,08-07-2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,1,0,No,No

In [46]:
df.loc[df["Do you have Panic attack?"] == "Yes", "Do you have Panic attack?"] = 1
df.loc[df["Do you have Panic attack?"] == "No", "Do you have Panic attack?"] = 0
df.sample(10)

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
73,09-07-2020 06:57,Male,18.0,Biomedical science,year 1,0 - 1.99,No,0,0,0,No
41,08-07-2020 14:57,Female,22.0,Engineering,year 4,3.50 - 4.00,No,0,0,0,No
92,13-07-2020 14:48,Female,19.0,KOE,year 2,3.00 - 3.49,Yes,1,0,0,No
59,08-07-2020 16:34,Female,23.0,Benl,year 1,3.00 - 3.49,No,0,0,0,No
52,08-07-2020 15:47,Female,19.0,Biomedical science,year 3,3.00 - 3.49,No,0,0,0,No
89,13-07-2020 11:54,Male,24.0,Engineering,Year 2,2.00 - 2.49,No,0,0,1,No
9,08-07-2020 12:39,Male,18.0,Irkhs,year 1,3.50 - 4.00,No,0,1,1,No
40,08-07-2020 14:57,Female,24.0,BIT,Year 3,3.00 - 3.49,No,0,1,0,No
64,08-07-2020 17:46,Female,24.0,Engine,year 1,3.50 - 4.00,No,0,0,0,No
31,08-07-2020 14:29,Male,18.0,BCS,year 2,3.00 - 3.49,No,0,0,0,No

In [47]:
df.loc[df["Did you seek any specialist for a treatment?"] == "Yes", "Did you seek any specialist for a treatment?"] = 1
df.loc[df["Did you seek any specialist for a treatment?"] == "No", "Did you seek any specialist for a treatment?"] = 0
df.sample(5)

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
67,08-07-2020 18:11,Male,19.0,MHSC,Year 3,3.00 - 3.49,Yes,1,0,1,0
65,08-07-2020 17:50,Female,23.0,Econs,year 1,3.50 - 4.00,No,1,1,0,0
90,13-07-2020 13:57,Female,23.0,DIPLOMA TESL,Year 3,3.50 - 4.00,No,0,0,1,0
83,13-07-2020 10:12,Female,19.0,Pendidikan Islam,Year 2,3.00 - 3.49,No,0,0,0,0
29,08-07-2020 14:05,Female,24.0,BCS,year 4,3.50 - 4.00,No,0,0,0,0

In [48]:
df.loc[df["Marital status"] == "Yes", "Marital status"] = 1
df.loc[df["Marital status"] == "No", "Marital status"] = 0
df.sample(5)

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
37,08-07-2020 14:45,Female,19.0,BIT,year 1,2.50 - 2.99,0,1,1,1,0
62,08-07-2020 17:05,Female,18.0,CTS,Year 1,3.50 - 4.00,0,0,0,1,0
49,08-07-2020 15:18,Female,24.0,BCS,year 3,3.50 - 4.00,0,0,0,1,0
97,13-07-2020 21:21,Male,18.0,Engineering,Year 2,3.00 - 3.49,0,1,1,0,0
26,08-07-2020 13:35,Female,19.0,Engineering,year 1,3.50 - 4.00,0,0,0,0,0

In [49]:
df.rename(columns={
    "Do you have Depression?": "Depression",
    "Do you have Anxiety?": "Anxiety",
    "What is your CGPA?": "CGPA",
    "marital status": "MaritalStatus",
    "Do you have Panic attack?" : "Panicattack",
    "Did you seek any specialist for a treatment?" : "Specialist",
    "Choose your gender" : "Gender",
    "What is your course?" : "Course",
    "Your current year of Study" : "Year"
}, inplace=True)

In [50]:
df

,Timestamp,Gender,Age,Course,Year,CGPA,Marital status,Depression,Anxiety,Panicattack,Specialist
0,08-07-2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,0,1,0,1,0
1,08-07-2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,0,0,1,0,0
2,08-07-2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,0,1,1,1,0
3,08-07-2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,1,1,0,0,0
4,08-07-2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
96,13-07-2020 19:56,Female,21.0,BCS,year 1,3.50 - 4.00,0,0,1,0,0
97,13-07-2020 21:21,Male,18.0,Engineering,Year 2,3.00 - 3.49,0,1,1,0,0
98,13-07-2020 21:22,Female,19.0,Nursing,Year 3,3.50 - 4.00,1,1,0,1,0
99,13-07-2020 21:23,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,0,0,0,0,0
100,18-07-2020 20:16,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,0,0,0,0,0

In [51]:
df.drop(columns=["Timestamp"], inplace=True)

In [52]:
df

,Gender,Age,Course,Year,CGPA,Marital status,Depression,Anxiety,Panicattack,Specialist
0,Female,18.0,Engineering,year 1,3.00 - 3.49,0,1,0,1,0
1,Male,21.0,Islamic education,year 2,3.00 - 3.49,0,0,1,0,0
2,Male,19.0,BIT,Year 1,3.00 - 3.49,0,1,1,1,0
3,Female,22.0,Laws,year 3,3.00 - 3.49,1,1,0,0,0
4,Male,23.0,Mathemathics,year 4,3.00 - 3.49,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
96,Female,21.0,BCS,year 1,3.50 - 4.00,0,0,1,0,0
97,Male,18.0,Engineering,Year 2,3.00 - 3.49,0,1,1,0,0
98,Female,19.0,Nursing,Year 3,3.50 - 4.00,1,1,0,1,0
99,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,0,0,0,0,0
100,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,0,0,0,0,0